name: Publish Package to pypi

on:
  release:
    types: [created]
  workflow_dispatch:

permissions: write-all

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install maturin
        run: uv pip install maturin --system
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Cargo tarpaulin
        run: cargo install cargo-tarpaulin
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
          node-version: 22
          cache: 'pnpm'
      - run: pnpm i
      - name: Setup
        run: |
          pnpm build
          pnpm lint
          pnpm test
      - name: Publish to cargo
        run: |
          cd libs/braillify
          cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Publish to pypi
        run: |
          cd packages/python
          uv publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}


